i-love-flamingo/flamingo-commerce

cart/module.go
After a successful order, a flash message is added to the session to display a success page with all order details in the frontend. Due to the refactoring of the payment, the current implementation cannot be saved in the session. Therefore the successAction displays the template as if the session was expired. This PR registers the cart.PaymentSelection structure with gob.Register to make it serializable in the session.
=> commerce/cart: Fix cart.PaymentSelection not serialisable during place order

cart/application/cartService.go
checkProductQtyRestrictions needs the difference and not the total qty of updated items.
=> commerce/cart: Fix checkProductQtyRestrictions call during UpdateItemQty

cart/application/cartReceiver_test.go
Config struct of cartService was updated in #8, change wasn't applied to the test cases.
=> cart: Fix failing cart tests due to incomplete config struct

cart/application/cartReceiver_test.go, cart/application/eventPublishing.go, cart/infrastructure/InMemoryBehaviour.go, cart/infrastructure/InMemoryBehaviour_test.go
If the payment selection is reset, we should dispatch an event to inform the frontend to generate a new payment selection.
fixed some linting errors in cartReceiver_test.go as well.
=> cart: Add event that fires when the payment selection was reset

cart/application/cartReceiver_test.go, cart/application/cartService.go, cart/application/cartService_test.go, cart/application/eventPublishing.go, cart/domain/cart/cartServicePorts.go, cart/infrastructure/InMemoryBehaviour.go, cart/infrastructure/InMemoryBehaviour_test.go
All cart modify behaviour functions can return a list of events that the
cart service shall dispatch in the end.
=> cart: add possibility to dictate events for later dispatching

cart/domain/decorator/cartDecorator.go, product/domain/productBasics.go, product/domain/productBasics_test.go
Use net prices to ignore taxes for minimum spend, use item qty to calculate min instead of relative rate
=> cart: Fix loyalty charges

Readme.md, cart/domain/validation/restrictionService.go, cart/domain/validation/restrictionService_test.go
Name is eventually needed to discern which restrictor changed the max (aka the "strictest") and show it in the frontend.
=> Adding Name to Restrictor Interface

cart/application/cartService.go, cart/domain/validation/restrictionService.go, cart/domain/validation/restrictionService_test.go, order/domain/order.go
Allow restrictors to restrict quantities based on delivery code.
This PR also adds Attributes to OrderItems to be more flexible in the future.
=> cart: Add delivery code to restrictors

cart/domain/decorator/cartDecorator.go
The cart decorator does not return a usable decorated item in case the product service was not able to fetch an product.
This scenario can arise as soon as a product is added to the cart and later removed from storage.
The decorator must provide a valid fallback product.
=> Fix cart decorator issue in case of missing product

cart/application/cartReceiver.go
The ErrCacheIsInvalid on fetching a cached card must not result into a warning or error level log message.
=> cart: handle and log error on invalid cache

cart/domain/cart/cart.go, cart/domain/cart/delivery.go, cart/domain/cart/item.go
Use preallocated slices in cart where possible for loop/append operations to reduce slice growth.
The affected methods may be called rather often for cart pages.
=> cart: use preallocated slices where possible

cart/domain/cart/cart.go, cart/infrastructure/InMemoryBehaviour.go, cart/infrastructure/InMemoryBehaviour_test.go
The balance was an incomplete first idea, it is much clearer for the gift card to include an applied price and a remaining price. With this any client can differ between those two values for his logic.
=> cart: Split up balance of giftcards

checkout/interfaces/controller/checkoutcontroller.go
In DEVMode: restore the last stored transaction flash data (orderdata) so a frontend developer can reload the successpage (without creating orders again and again) while working on success template
=> In DEVMode: restore the last stored transaction flash data

cart/domain/cart/paymentselection.go, cart/domain/cart/paymentselection_test.go
Currently the paymentsplit cannot be parsed to json as the key in the map is a complex object. I suggest to parse the information in this object to a string key to provide marshalling and unmarshalling behaviour.
In order to migitate overwrite of keys due to empty methods or chargetypes, I suggest to throw an error in case such a value is encountered.
=> cart: add json de-/serialization of PaymentSplit

cart/domain/cart/delivery_test.go, cart/domain/cart/discount.go, cart/domain/cart/discount_test.go, cart/domain/cart/item.go, cart/domain/cart/item_test.go, cart/domain/decorator/cartDecorator.go, cart/domain/decorator/discount.go, cart/domain/decorator/discount_test.go, cart/domain/testutils/utils.go
Currently Discounts are available on Item level (ItemDiscounts) but not on a delivery or a cart level. These information may be useful for the client, therefore I suggest a new generic structure of Discounts that are available on Item, Delivery and Cart level. ~~The discounts are merged by their title and a newly introduced type~~. 
The discounts are merged by their campaign code, which is defined as a code that is a underlying identifier.
=> cart: Resctructure discounts

price/domain/price.go, price/domain/price_test.go
Currently split in payables does not function correctly when called with negative values as the loop 
`	
for i := 0; i < int(splittedAmountModulo); i++ {
splittedAmounts[i] = splittedAmounts[i] + 1
}
`
Does not move around the overflowing cent.
Therefore i suggest to multiply negative values with -1 to achieve the correct behaviour.
=> price: add handling of negative values in split in payables

product/interfaces/templatefunctions/findProducts.go, product/interfaces/templatefunctions/findProducts_test.go
For example, selecting multiple delivery methods or brands was not possible.
With this fix it's allowed to either
- send an filter list with strings as values, like { 'brand': 'apple' } (the old way for backwards compatibility
- or send a list with an array of strings, like { 'brand': ['apple', 'samsung'] }
=> Bugfix: Allow filters with multiple values

cart/domain/cart/paymentselection_test.go, price/domain/price.go, price/domain/price_test.go
As a client I would be able to have multiple charges of a certain type without overwriting each other. Also I want to pass arbitrary additional information with my charges.
I suggest a map on Charges for additional information and moreover added a ChargeQualifier.
=> price: Allow multiple charges of the same type

product/Readme.md, product/application/urlService.go, product/application/urlService_test.go, product/domain/productBasics.go, product/module.go
Allow to use an url slug provided by product data by
- adding a configuration with fallback to slug generation if not configured
- add a configuration for the target attribute within the product data
refs 202816
=> product: allow to use provided urlslug from product data

cart/domain/cart/paymentselection.go, cart/domain/cart/paymentselection_test.go, cart/domain/cart/paymentselection_wb_test.go
Currently for the calculation of splitted charges we need zero charges. These charges do not make sense for a clients payment (0 charges cannot be payed). 
Therefore before the payment selection is generated for the client I suggest to filter out 
zero charges.
=> cart: remove zero charges from payment selection

checkout/application/orderService.go
Currently as a client I can only place  a cart with payment processing which is taken from my cache or freshly fetched by my cartReceiverService implementation.
I suggest to provide a function to explicitly pass a cart for order placement and payment processing.
=> checkout: enable cart to be passed for order placement

cart/domain/cart/paymentselection.go, cart/domain/cart/paymentselection_wb_test.go
With floating points number there is sometimes the need to enable payables and sometimes not. To make the behaviour less flaky, I would suggest to provide a function to finalise the payment charges (remove zero charges, get payables)
=> cart: Make big float split more robust

cart/Changelog.md, cart/domain/cart/cart.go, cart/infrastructure/InMemoryBehaviour.go, cart/interfaces/controller/forms/billingform.go, checkout/application/orderService.go
Fix typo in accordance to bug:
https://targetprocess.aoe.com/restui/board.aspx?#page=bug/203974&appConfig=eyJhY2lkIjoiNDc3MUI4MzkxNjdDQkZERTVFRTI2REQzQTY4NUNEMEYifQ
This does break flamingo-om3 and KSO.
AKL is unaffected.
=> cart: Fix typo 'BillingAdress' to 'BillingAddress'

cart/application/cartReceiver.go, cart/application/cartReceiver_test.go, cart/application/cartService.go, cart/domain/cart/cartServicePorts.go, cart/domain/placeorder/placeorder.go, cart/infrastructure/email/emailplaceorder.go, cart/infrastructure/inMemoryCustomerCartserviceAdapter.go, cart/infrastructure/inMemoryGuestCartserviceAdapter.go, checkout/Changelog.md, checkout/Readme.md, checkout/application/orderService.go, checkout/application/orderService_test.go, checkout/interfaces/controller/checkoutcontroller.go, checkout/module.go, payment/Changelog.md, payment/Readme.md, payment/domain/payment.go, payment/interfaces/controller/paymentapicontroller.go, payment/interfaces/offlinePaymentGateway.go, payment/interfaces/webpayment.go, payment/module.go, payment/module_test.go
Currently the order is placed after the payment process is finished. Due to cross device payment options some payment adapters could demand an early order placement and flamingo-commerce should offer an polling option ask the payment adapter in which state the payment flow is. According to that payment status certain messages can be displayed to the customer.
To avoid polluting the SubmitCheckoutAction/PlaceOrderAction this handling should happen in a separate action which should display an intermediate payment page. This page can then react to the current payment flow status and display certain messages through polling or redirecting to the SuccessAction if the payment adapter tells us to do so.
=> payment/checkout: Enable payment / checkout to early place order  and show a robust payment page

cart/application/cartService.go
The current implementation does not work as expected as the cart pointer needs to be overwritten for the defer function.
=> cart: Use returned cart for defer functions, otherwise we would use old carts

checkout/interfaces/controller/checkoutcontroller.go
This can happen if the user hits the back button and leaves the payment status page.
=> checkout: Add check if payment already in process and redirect to payment status page

checkout/application/orderService.go
The orderservice should pass through arbitrary errors from the infrastructure layer instead of overwriting it. 
The client might want to react on custom errors depending on the situation.
=> checkout: orderservice should pass through errors

checkout/interfaces/controller/checkoutcontroller.go, payment/domain/payment.go
cart: Reopen cart in case of a payment flow issue to keep checkout still usable. Handle PaymentFlowStatusCancelled accordingly.
=> cart: Reopen cart in case of a payment flow issue

cart/application/cartService.go
When working with products we always need to check if its an configurable and get the active variant to be able to restrict and validate the variant instead of the base product.
=> cart: Fix validators/restrictors not able to handle configurable product

cart/infrastructure/InMemoryBehaviour.go
It was not possible to add a variant to the in-memory cart because it always tried to add the configurable product instead of the selected variant. It then failed because configurable product are not saleable.
Now, when building the cart item we get the product with active variant first.
=> Allow adding variants to in-memory cart

cart/Changelog.md, cart/application/cartService.go, checkout/application/orderService.go
Using the cached cart (after already completing the cart) may potentially return an empty cart from the cart receiver service if no cache is used or the cache died.
=> cart + checkout: Don't use cached cart when placing order

search/application/searchService.go, search/interfaces/controller.go
Background:
- interface layer of product and category package depend on search package - e.g. they reuse dto and graphQL types
- it should be possible to reuse them without a searchservice adapter. Currently thats not possible since in Module the controller and its dependencies request a Searchservice
=> We should make this DI optional
=> search: Make searchService implementation optional 

category/domain/category.go
A proper attribute struct was introduce recently for categories. To make the values more accessible we added two "toString" functions to return a concatenated string of all the values of an attribute, and all the values of an attribute value.
=> Make toString function for attributes

cart/domain/cart/cart.go
Coupon codes sometimes need to have additional data. e.g. restrictions that can only be evaluated later in process.
=> Add custom attributes to CouponCode

cart/application/cartService.go, cart/domain/cart/cart.go
A new type alias for applied coupons was introduced in the cart model, this messed up the GraphQL mapping. This commit reverts the type alias while maintaining the needed behaviour in cartService.go
=> cart: fix GraphQL for cart, due to new type alias in cart model

cart/Changelog.md, cart/application/cartReceiver_test.go, cart/application/cartService.go, cart/application/cartService_test.go, cart/domain/events/eventPublishing.go, cart/domain/events/events.go
Hello friends,
currently the `AddToCartEvent` and `ChangedQtyInCartEvent` are published before the cart
has been updated in the cache as they are not part of the deferred events.
When listening to the event as a client, I want to receive the updated cart for evaluation.
This PR addresses this issue by adding the cart to said events, analogue to the `OrderPlacedEvent `.
I think this is how this was intended anyway, as the function `publishAddtoCartEvent` already receives the cart, but it is not used.
Another issue is that the `ChangedQtyInCartEvent` is thrown before the Cart is even updated, which means that the event is thrown even if there is an error with the update.
I am aware that this is a breaking change, but I think the behaviour so far is not correct.
Please review!
=> cart: Adjust behaviour of add event and update qty event

cart/domain/cart/cart.go, cart/domain/cart/cart_test.go
#184 will be solved with this pull request. Old function stays the same, but there is a ProductCountUnique now, that will check across deliveries.
=> Behaviour of ProductCount() in cart.go should be unique #184

checkout/interfaces/controller/checkoutcontroller.go
If you try to place two orders right after each other, the second order will show the success page of the first order. Also, the second order is not placed and you keep your cart, despite seeing a success page. This is because the last placed order is still contained in the session. Then, the placeOrderActions only clears the session and does not place an order (see https://github.com/i-love-flamingo/flamingo-commerce/blob/650f15f00af5799dc2779165c785bbf4341ffbc0/checkout/interfaces/controller/checkoutcontroller.go#L256)
To avoid that behavior, we clear the last placed order right before showing the success page.
=> clear last placed order before showing the success page

CHANGELOG.md, w3cdatalayer/application/factory.go
If the router fails to build an absolute url, the datalayer would cause a panic. To avoid that, we now check the error and provide an empty url instead.
=> datalayer: fix panic if not able to build absolute url

CHANGELOG.md
Most recent changes / versions should be at the top of the CHANGELOG, this reorders the changelog entries.
=> rearrange CHANGELOG.md so most recent version is at top

CHANGELOG.md, checkout/application/orderService.go
This pull request is about cleaning up the metrics in the checkout process. Currently we only expose failures for every error that occurs while trying to place an order.
By this change new metrics will be exposed that introduce measurement for other issues that happen. Also the failures will get much more meaningful
=> checkout: cleanup metrics

CHANGELOG.md
Since there are quite some changes we should release v3.2.0 and continue with v3.3.0
=> Update changelog to mark beginning of new v3.3.0

CHANGELOG.md, checkout/Changelog.md, checkout/Readme.md, checkout/application/orderService.go, checkout/application/orderService_test.go, checkout/module.go
When using the place order state machine, one of the first steps during the process is already validating the cart.
Afterwards the cart is closed and stored inside the context store.
When then later placing the order the OrderService performs the cart validation again.
At this time the cart is already closed and if a validator tries to fetch the cart from the session, an empty cart returns which can lead to invalid validation results.
=> checkout: optional cart validation before place order

CHANGELOG.md, checkout/application/placeorder/coordinator.go, checkout/domain/placeorder/process/process.go
checkout: Add metrics to the standard place order process.
The following open census metrics are now exposed:
-  no of starts w/ new uuid
- flamingo_standard_place_order_new_uuid{area=""} 1
-  no of runs for each state (bucket)
- example for a state: flamingo_standard_place_order_processed_state{area="-",state="CompleteCart"} 3
-  no of failed state transitions by state name (bucket)
- example for a state: flamingo_standard_place_order_failed_state_transition{area="-",state="CompleteCart"} 1
=> checkout: Add metrics to the standard place order process.

breadcrumbs/module_test.go, category/module_test.go, customer/module_test.go, order/module.go, order/module_test.go, payment/module_test.go, price/module_test.go, product/module_test.go, search/module_test.go, w3cdatalayer/module_test.go
A basic Flamingo module should always include an according test case that ensures that dingo dependencies and config is working properly. 
This PR adds the missing ones and updates existing ones for better test coverage.
=> Add module tests to all modules lacking one

CHANGELOG.md, cart/Changelog.md, cart/application/cartReceiver_test.go, cart/application/cartService.go, cart/domain/validation/itemValidator.go, checkout/Changelog.md, checkout/Readme.md, checkout/application/orderService.go, checkout/application/orderService_test.go, checkout/module.go
The cart item validation gets the cart passed as argument to prevent single validator implementations to load the cart again from different sources (like session or cart service)
This assures that the correct cart is validated
=> cart: item validation must rely on given cart

cart/application/cartService.go
If a product can't be added to the cart due to the item validator this is a normal behaviour, therefore it should be logged on level INFO.
The same applies to the items that are qty restricted.
=> cart: Use a lower log level if a product can't be added to the cart

CHANGELOG.md, product/interfaces/controller/controller.go, product/interfaces/controller/controller_test.go
The viewVariantOption struct is missing the unit of the specific variant to be able to display it in the template.
=> product: expose unit codes of variant attributes

CHANGELOG.md, cart/application/cartService.go, cart/application/cartService_test.go, cart/infrastructure/InMemoryBehaviour.go, cart/infrastructure/InMemoryBehaviour_test.go, checkout/application/orderService.go, checkout/interfaces/controller/checkoutcontroller.go, search/interfaces/graphql/graphql.go, search/interfaces/graphql/service.go, test/integrationtest/projecttest/config/config.yml, test/integrationtest/projecttest/modules/placeorder/fake_service.go, test/integrationtest/projecttest/tests/frontend/checkout_test.go
In case of error during payment always redirect back to checkout/review page in stead of rendering the template under a different route
Currently in case of a error during payment/placing the order we just render the checkout / review template again on the same route.
If the user then reloads the page he is still on the placeorder route and will trigger the error again or cause other potential side effects.
Its therefore better to send him back on the checkout route and render the error in the matching action. So that the customer then can start a new try.
=> checkout: Improve controller error handling

CHANGELOG.md, cart/application/cartCache.go, cart/application/cartCache_test.go, cart/application/cartService.go
During the place order process the cached cart is deleted twice (Once when completing the current cart and once when placing the cart):
https://github.com/i-love-flamingo/flamingo-commerce/blob/master/cart/application/cartService.go#L517
https://github.com/i-love-flamingo/flamingo-commerce/blob/master/cart/application/cartService.go#L1013
The second call currently logs an error because the cache entry is not found. 
Adjusted the log level for that case.
=> cart: Adjust log level if cache entry not found for DeleteCartInCache

CHANGELOG.md, checkout/interfaces/controller/checkoutcontroller.go
When a payment is aborted/canceled the checkout controller regenerates a new idempotency key. If an early place happened the cart at this stage is potentially not accessible any more. We therefore need to first cancel the order / restore the cart before setting the new PaymentSelection / Idempotency Key.
This PR changes the orders of the calls.
=> checkout: Generate a new idempotency key after cart restore

CHANGELOG.md, cart/domain/cart/paymentselection_test.go, price/domain/price.go, product/Readme.md, product/infrastructure/fake/helper.go, product/infrastructure/fake/productservice.go, product/infrastructure/fake/searchservice.go, product/module.go, test/integrationtest/projecttest/config/config.yml, test/integrationtest/projecttest/tests/graphql/testdata/products/json_simple.json
Currently, fake services are very static, in case you need something special, a custom attribute, variant options, etc. developers have to either create a pull request or implement own fake service in their projects. This feature allows developers to define/extend current fake products with their own versions of it.
=> product: Add feature to the product fakeservice to use json files as the source.

cart/interfaces/templatefunctions/getItemAdjustment.go, cart/interfaces/templatefunctions/getItemAdjustment_test.go
At the moment a frontend can not determine the reason why an item in the cart was deleted/had its quantity adjusted.
=> Add Reason to qty adjustment result

.github/workflows/main.yml, Readme.md
After switching from travis-ci.org to travis-ci.com we should use the proper URLs for badges.
Also, the newly added GitHub Actions come with badges
=> Rename GitHub Action workflow and update badges in readme

product/domain/productBasics.go, product/domain/productBasics_test.go
Due to a previous PR(#236) a breaking change was introduced when handling the Values() func. This reverts the breaking part and keeps the trimming that was introduced on purpose.
=> product: partially revert attribute Values() func to be non breaking

CHANGELOG.md, sourcing/domain/service.go, sourcing/domain/service_test.go
Implementing StockProviders require the deliveryInfo for specific stock checks.
=> sourcing: Add deliveryInfo to interface StockProvider GetStock

CHANGELOG.md, cart/application/cartService_test.go, cart/infrastructure/defaultCartBehaviour_test.go, cart/infrastructure/inMemoryStorage.go
The init func of InMemoryCartStorage is intended to init the storage if required as well as the sync.Locker to prevent concurrent operations on the storage. 
This handling does not solve the concurrent calls, as "it is already too late", a locking must be done before the first access to the storage map is done. 
The refactored implementation uses Inject to ensure that storage and Locker have been initialized to correctly lock on each receiver.
=> cart: Trying to fix race on in memory cart storage

product/module.go
Use override binding when fake services are active to enforce those.
=> product: Override existing bindings for fake services

category/module.go
To easily test categories the fake service should always be taken into favour.
=> category: fake service should always override existing bindings

CHANGELOG.md, cart/domain/cart/delivery_test.go, cart/domain/cart/item.go, cart/domain/cart/item_test.go
The split adds the moving cents to the first ones, resulting in
having the smallest prices at the end but since discounts are
negative, we need to reverse it to ensure that a split of the row
totals has the rounding cents at the same positions
=> cart: Reverse the order of split items discount

CHANGELOG.md, cart/domain/cart/paymentselection_test.go, price/domain/price.go, price/domain/price_test.go
Currently, all our web APIs expose the prices not rounded, this leads to rounding implementations in the consumer. To avoid this we round all prices by default when requested as JSON.
=> price: Convert all prices to payable when marshalling to JSON

CHANGELOG.md, checkout/interfaces/controller/checkoutcontroller.go
If the payment provider enforces an early place order and the payment is then aborted we never renew the order id.
=> checkout: reserve a new order id if early place order has payment issues

price/application/service.go, price/application/service_test.go
The underlying library used for formatting prices already supports different precisions for different currencies.
Default will still be precision 2, but can now be overwritten.
=> price: format price using configured precision

CHANGELOG.md, cart/application/eventHandling.go
If the customer cart already has some items attempting to apply the guest carts payment selection will most likely log an error since the merged carts GrandTotal will not match the payment selection total.
Similarly, coupons and giftcards may affect the GrandTotal and should be applied before updating the payment selection.
=> fix(cart): only apply guest cart payment selection after coupons/discounts and if customer cart is empty

CHANGELOG.md, cart/infrastructure/defaultCartBehaviour.go
Currently `updateItem` on the `defaultCartBehavior` (Memory Cart) is lacking support for setting the AdditionalData. This PR is adding AdditionalData from the Update command to the item.
=> feat(cart): add support for AdditionalData on CartItem level for the defaultCartBehaviour

CHANGELOG.md, product/domain/productTypeBundle.go, product/domain/productTypeBundle_test.go
As prior passing all choices with qty of zero have been required. Now optional choices with qty of zero can be omitted.
=> Add to cart of bundle products fails for missing of none required bundle choices

CHANGELOG.md, cart/interfaces/graphql/dto/dto.go, cart/interfaces/graphql/schema.graphql, product/interfaces/graphql/product/dto/productdto.go, product/interfaces/graphql/resolver.go, product/interfaces/graphql/schema.graphql, test/integrationtest/projecttest/graphql/generated.go, test/integrationtest/projecttest/graphql/schema/flamingo.me_flamingo-commerce_v3_cart_interfaces_graphql-Service.graphql, test/integrationtest/projecttest/graphql/schema/flamingo.me_flamingo-commerce_v3_product_interfaces_graphql-Service.graphql, test/integrationtest/projecttest/tests/graphql/testdata/commerce_cart_AddBundleToCart.graphql, test/integrationtest/projecttest/tests/graphql/testdata/commerce_cart_AddBundleToCart_Update_Qty_Helper.graphql
Falling back to minimum values or 1 was a bad design choice. The consumer of graphql should clearly state with what amount a bundle choice should be added to the cart / fetched from the product service
=> chore(bundles): Require explicit qty amounts when it comes to bundle choices

sourcing/domain/service.go
The err from above can be nil here
=> fix(sourcing): use correct error to generate the message

.github/workflows/golangci-lint.yml, .golangci.yml, CHANGELOG.md, checkout/application/orderService.go, checkout/application/orderService_test.go, checkout/module.go
In case you are using the place order state machine, cart is already validated in the dedicated ValidatCart state. So no need to additionally validate it during PlaceOrder state.
=> feat(checkout/orderservice): Introduce flag to skip cart validation during place order

cart/application/cartCache.go, cart/application/cartReceiver_test.go, cart/application/cartService.go, cart/domain/cart/cart.go, cart/domain/cart/cartServicePorts.go, cart/infrastructure/defaultCartBehaviour.go, cart/infrastructure/defaultCartBehaviour_test.go, go.mod, product/domain/productService.go, product/interfaces/controller/apicontroller.go, product/interfaces/controller/controller.go, w3cdatalayer/application/factory.go, w3cdatalayer/application/service.go
The topic was started in 2021 (see #334) and is now actually in a mergeable state.. 🎉
=> chore: Replace github.com/pkg/errors with Go core error package
