payment/domain/payment.go, payment/interfaces/offlinePaymentGateway.go, payment/interfaces/webpayment.go
Adding Ability for fetching a workflow without needing a web.Response
=> Webpayment changes

cart/domain/cart/cart.go, cart/domain/cart/cartDecorator.go, cart/domain/cart/payment.go, price/domain/price.go, product/domain/productBasics.go
charges are not directly coupled with products and can also be used for
shipments and totals
=> move charges to price domain

cart/Readme.md, cart/interfaces/templatefunctions/getCart.go
Small update for the readme and the comments
=> Fix  - fix docu regarding templatefunction getDecoratedCart and fix tipo

cart/application/cartService.go
A client may want to know which and how his implemented restrictions failed. Therefore it should be passed with the error, as returning both "result" and "error" would not be idiomatic.
=> cart: Add dedicated restriction error so clients can react to restrictions

category/interfaces/controller/controller.go, category/module_test.go
- Fix spelling
- Add dingo  module test
- Remove unused logger
- Avoid config nil pointer exception
- Make Inject chainable
- Remove call to deprecated router.URL
=> category: Minor improvements, add module test, remove unused dependency

cart/application/cartService.go
Allow more lightweight operations on cartservice.ReserveOrderID if the cart already contains a reserved order ID: just do nothing and return the cart - drop generation and update
=> cartservice: noop on ReserveOrderID if already set

cart/domain/cart/cart.go
Just some minor codestyle fixes on cart.go
=> Cart minor codestyle fixes

cart/interfaces/controller/cartcontroller.go
=> T#199994 [BE] Catch the update cart error

cart/application/cartService.go, cart/domain/cart/cartServicePorts.go, cart/infrastructure/InMemoryBehaviour.go, cart/infrastructure/InMemoryBehaviour_test.go, cart/interfaces/controller/cartapicontroller.go, cart/module.go, cart/module_test.go
This PR allows the user to remove already applied vouchers from card.
=> cart: Add option to remove applied voucher from cart

cart/application/cartService.go, cart/domain/cart/cart.go, cart/domain/cart/cartServicePorts.go, cart/infrastructure/InMemoryBehaviour.go, cart/infrastructure/InMemoryBehaviour_test.go, cart/interfaces/controller/cartapicontroller.go, cart/module.go
Hola! I would like to add giftcard functionality to the cart contract. They should be handled separately from vouchers, as their implementation could be different. My suggestion is to enhance the cart behaviour interface with functions analogue to vouchers.
=> Enhance cart behaviour contract with giftcard functionality

cart/domain/cart/cart.go
Implement setter to add applied gift carts.
=> Update cart builder

cart/application/cartService.go, cart/domain/cart/cartServicePorts.go, cart/interfaces/controller/cartapicontroller.go, cart/module.go
We should align combined fields with giftcards and vouchers. Also fix spelling, its GiftCar**d** not GiftCar**t**
=> cart: Fix formatting and use abstract behaviour

checkout/interfaces/controller/checkoutcontroller.go
Handle the additional form fields for terms & conditions and privacy policy in SubmitAction if review step is skipped.
=> checkout: handle terms&conditions and privacy policy in SubmitAction

checkout/application/orderService.go
Use the background context during order placement to prevent context cancel by clients.
=> checkout: place order in background

checkout/application/orderService.go
The freshly invented checkout context is missing the current request - which is required handling/placing an order.
=> checkout: the checkout context is missing the current request

cart/domain/cart/paymentselection.go
I noticed that the handling of the error was missing and the comparison of the big float was a bit flaky.
=> cart: paymentselection, fix comparison of big floats

product/Readme.md, product/interfaces/templatefunctions/findProducts.go, product/interfaces/templatefunctions/findProducts_test.go
Refactor the FindProducts function
=> Allow filters with multiple values

cart/Changelog.md, cart/domain/cart/delivery.go, cart/domain/cart/discount.go, cart/domain/cart/discount_test.go, cart/domain/decorator/discount_test.go, cart/domain/testutils/utils.go
Replaced ShippingItem.DiscountAmount with ShippingItem.AppliedDiscounts.
ShippingItem not implements the WithDiscount interface.
=> 204496: Fix promos not affecting shipping cost

cart/application/cartService.go, cart/domain/placeorder/placeorder.go, cart/infrastructure/email/emailplaceorder.go
Cancel Order functions needs Customer and Guest functionality. Split up CancelOrder into Guest and Customer versions.
=> cart: Enhance cancel order customer guest

category/interfaces/controller/controller.go, search/domain/filter.go, search/utils/pagination.go, search/utils/pagination_test.go
Pagination need next and previous page optional
Category Controller does not use correct typed Filter to init search 
And the search Filter need public accessors for its specific data
=> Improve search

checkout/application/orderService.go
Change to OrderService flow to first place the order before confirming the payment via the supplied payment gateway. This could potentially improve order placement stability since confirming isn't mandatory and could be handled later by the order management system.
=> checkout: OrderService place order earlier to be more fault tolerant

checkout/module.go
=> code style fix

cart/application/cartReceiver.go, cart/application/cartService.go, cart/application/eventHandling.go, cart/domain/cart/cartServicePorts.go, cart/module.go
1) It is hard to test cartService because of Authentication and the problem to mock it => add Interfaces
2) Cart Merge currently has problems:
- No BillingAddress is merged
- AdditionalInfos are missing in Delivery
- its not handled as a "detached transaction" and a canceled context might kick in
=> cart: Fix Cart Merging

cart/application/cartCache_test.go, cart/domain/cart/cart.go, cart/domain/cart/delivery.go, cart/domain/cart/paymentselection.go, cart/domain/decorator/cartDecorator.go, cart/domain/placeorder/placeorder.go, cart/infrastructure/InMemoryBehaviour.go, cart/interfaces/controller/cartapicontroller.go, cart/interfaces/controller/forms/deliveryform.go, checkout/application/orderService.go, checkout/interfaces/controller/checkoutcontroller.go, customer/infrastructure/nilCustomer.go, price/domain/price.go, product/domain/productBasics.go, product/interfaces/templatefunctions/findProducts.go, search/domain/filter.go, w3cdatalayer/application/eventhandling.go, w3cdatalayer/domain/datalayer.go
PR fixes commonly misspelled English words, found with: https://github.com/client9/misspell
=> Fix various spelling errors

checkout/application/orderService.go
=> checkout: OrderService place order after payment completion

product/domain/productBasics.go
some documentation as requested by @danielpoe
=> product: add documentation for product attribute struct

breadcrumbs/Readme.md
The documentation is wrong, the loop should be regarding the breadcrumb data.
=> Fix documentation

cart/Changelog.md, cart/domain/cart/cart.go, cart/domain/cart/giftcard.go, cart/domain/cart/giftcard_test.go, cart/domain/cart/paymentselection.go, cart/domain/cart/paymentselection_test.go, cart/domain/cart/paymentselection_wb_test.go, price/Readme.md, price/domain/price.go
Reverts the changes from this PR: https://github.com/i-love-flamingo/flamingo-commerce/pull/156
Also adds a function to filter a single gift card from a slice of gift cards by its code.
=> Revert charge custom attributes and add gift card filter function

docs/1. Introduction/3. Coding Conventions.md, docs/1. Introduction/4. Testing Conventions.md, docs/2. Flamingo Commerce Modules/08 w3c datalayer.md, docs/2. Flamingo Commerce Modules/08. W3C Datalayer.md, go.sum
We need to have conventions documented - this is a start
=> Add convention documentations

w3cdatalayer/application/service.go
- Improve linting
- Add language setter
- Fix logs
=> Extend data layer

cart/Changelog.md, cart/application/cartService.go, cart/application/eventHandling.go, cart/domain/cart/cartServicePorts.go, cart/infrastructure/InMemoryBehaviour.go, cart/interfaces/controller/cartapicontroller.go, cart/interfaces/controller/cartcontroller.go, cart/interfaces/graphql/mutationresolvers.go
Similar to being able to put some additonal data when updating an item this would enable one to provide some when adding a product.
=> cart: Add additonalData to AddRequest to be able to provide some when adding a product

CHANGELOG.md, product/application/searchService.go, product/infrastructure/fake/searchservice.go, search/application/searchService.go, search/domain/service.go
=> search: extend suggestions with type and additional attributes

CHANGELOG.md, product/infrastructure/fake/productservice.go, product/interfaces/controller/apicontroller.go, product/module.go, product/module_test.go, test/integrationtest/moduletest/product_test.go
Products Module should get a Rest API endpoint to get products
=> product: Add API controller

CHANGELOG.md, cart/application/cartService.go, cart/application/cartService_test.go, cart/domain/cart/cart.go, cart/domain/validation/restrictionService.go, cart/domain/validation/restrictionService_test.go, cart/interfaces/graphql/resolvers.go, checkout/Changelog.md, checkout/application/orderService.go, checkout/application/orderService_test.go, checkout/domain/sourcingengine.go, checkout/module.go, go.sum, sourcing/Readme.md, sourcing/application/service.go, sourcing/domain/restrictor/restrictor.go, sourcing/domain/restrictor/restrictor_test.go, sourcing/domain/service.go, sourcing/domain/service_test.go, sourcing/module.go, sourcing/module_test.go, test/integrationtest/projecttest/modules/cart/fake_qty_restrictor.go
Idea:
- Move out sourcing to own module - that optionaly can be used
- Get rid of sourcing logic in checkout (mark as depricated)
References Issue203
=> Newsourcing

product/infrastructure/fake/productservice.go, product/infrastructure/fake/searchservice.go
* Cleaned up inconsistencies in fake product structure
* Added simple facet "highlighting" to the product search fake services.
=> product: Extend product fakeservices

checkout/infrastructure/contextstore/redis_test.go, checkout/infrastructure/locker/redis_test.go
=> checkout: Improve docker based redis test, wait until redis is responding

CHANGELOG.md, cart/application/cartService.go, cart/application/cartService_test.go, cart/domain/cart/cart.go, cart/domain/cart/cart_test.go, cart/infrastructure/defaultCartBehaviour.go
=> cart: update CartDefaultBehaviour to return real clones

CHANGELOG.md, price/Readme.md, price/domain/price.go, price/domain/price_test.go
=> price: fix rounding of negative values

CHANGELOG.md, product/interfaces/graphql/product/dto/productdto_bundleproduct.go, product/interfaces/graphql/schema.graphql, test/integrationtest/projecttest/graphql/generated.go, test/integrationtest/projecttest/graphql/schema/flamingo.me_flamingo-commerce_v3_product_interfaces_graphql-Service.graphql, test/integrationtest/projecttest/tests/graphql/cart_test.go, test/integrationtest/projecttest/tests/graphql/testdata/Commerce_Cart_UpdateItemBundleConfig.graphql, test/integrationtest/projecttest/tests/graphql/testdata/Commerce_Cart_UpdateItemBundleConfig_one.graphql, test/integrationtest/projecttest/tests/graphql/testdata/commerce_cart_AddBundleToCart.graphql
Expose Active Option (product+qty) for bundle products within the cart items
=> chore(product): Expose Active Option (product+qty) for bundle products within the cart items

Readme.md
Removing typo from documentation.
=> Update Readme.md removing typo

CHANGELOG.md, product/interfaces/graphql/product/dto/productdto_bundleproduct.go
This PR adds exported method BundleConfiguration which exposes bundle configuration of the BundleProduct (in order to compare bundle products)
=> feat(271627): expose bundle configuration via method

checkout/infrastructure/contextstore/redis_test.go, checkout/infrastructure/locker/redis_test.go
As part of migration from Redis to Valkey
=> feat(309774): replace Redis container images with Valkey
